### PR TITLE
update font family body

### PR DESCRIPTION
**Pull request by moritzmock**
Related task: https://app.clickup.com/t/353nc82

### CODE REVIEW

**Review by mmalfertheiner — APPROVED** [review]

**Comment by moritzmock** [comment]
@mmalfertheiner, I am not able to merge it! Could you please do it?

**Comment by mmalfertheiner** [comment]
@moritzmock Could you check my comment in the other PR about the fonts. Would it be possible here as well?

**Comment by moritzmock** [comment]
To my understanding, the parameter `@apply font-sans;` originates from [tailwind](https://tailwindcss.com/docs/font-family), and since tailwind isn't installed in this project, it isn't working. 

image

**Review by mmalfertheiner — APPROVED** [review]

**Comment by moritzmock** [comment]
Could you please merge it? It is blocked again for me...

**Pull request merged**
